module.exports = {
	content: ["./src/**/*.{html,tsx}"],
	theme: {
		borderRadius: {
			16: "16px",
			full: "9999px",
		},
		spacing: {
			0: 0,
			1: "1px",
			4: "4px",
			5: "5px",
			7: "7px",
			8: "8px",
			12: "12px",
			16: "16px",
			18: "18px",
			20: "20px",
			24: "24px",
			32: "32px",
			40: "40px",
			80: "80px",
			56: "56px",
			280: "280px",
			360: "360px",
		},
		opacity: {
			8: 0.08,
			12: 0.12,
		},
		fontFamily: {
			sans: ["Roboto", "sans-serif"],
		},
		fontSize: {
			xs: [
				"12px",
				{
					lineHeight: "16px",
				},
			],
			titleMedium: [
				"16px",
				{
					lineHeight: "24px",
				},
			],
			sm: [
				"14px",
				{
					lineHeight: "20px",
				},
			],
			lg: [
				"28px",
				{
					lineHeight: "36px",
				},
			],
			xl: [
				"45px",
				{
					lineHeight: "52px",
				},
			],
		},
		colors: {
			primary: "#AA352A",
			onPrimary: "#FFFFFF",
			primaryContainer: "#FFDAD5",
			onPrimaryContainer: "#410001",
			secondary: "#7E544E",
			onSecondary: "#FFFFFF",
			secondaryContainer: "#FFDAD5",
			onSecondaryContainer: "#31130F",
			onSecondaryContainerHovered: "rgba(49,19,15,0.08)",
			tertiary: "#755B1B",
			onTertiary: "#FFFFFF",
			tertiaryContainer: "#FFDF9D",
			onTertiaryContainer: "#251A00",
			error: "#BA1A1A",
			onError: "#FFFFFF",
			errorContainer: "#FFDAD6",
			onErrorContainer: "#410002",
			background: "#FFFBFF",
			onBackground: "#201A19",
			surface: "#FFFBFF",
			onSurface: "#201A19",
			surfaceVariant: "#F5DDDA",
			onSurfaceVariant: "#534341",
			outline: "#857370",
			shadow: "#000000",
			inverseSurface: "#362F2E",
			inverseOnSurface: "#FBEEEC",
			inversePrimary: "#FFB4A9",
			surfaceTint: "#AA352A",
			surfaceTintColor: "#AA352A",
			dark: {
				primary: "#FFB4A9",
				onPrimary: "#680203",
				primaryContainer: "#891D16",
				onPrimaryContainer: "#FFDAD5",
				secondary: "#F0B9B2",
				onSecondary: "#492722",
				secondaryContainer: "#633D37",
				onSecondaryContainer: "#FFDAD5",
				tertiary: "#E5C278",
				onTertiary: "#3F2E00",
				tertiaryContainer: "#5B4302",
				onTertiaryContainer: "#FFDF9D",
				error: "#FFB4AB",
				onError: "#690005",
				errorContainer: "#93000A",
				onErrorContainer: "#FFB4AB",
				background: "#201A19",
				onBackground: "#EDE0DE",
				surface: "#201A19",
				onSurface: "#EDE0DE",
				surfaceVariant: "#534341",
				onSurfaceVariant: "#D8C2BE",
				outline: "#A08C89",
				shadow: "#000000",
				inverseSurface: "#EDE0DE",
				inverseOnSurface: "#362F2E",
				inversePrimary: "#AA352A",
				surfaceTint: "#FFB4A9",
				surfaceTintColor: "#FFB4A9",
			},
		},
		extend: {
			gridTemplateColumns: {
				listDetailViewClosed: "max-content auto ",
				listDetailViewOpen: "max-content auto 30%",
			},
			keyframes: {
				ripple: {
					"75%, 100%": {
						transform: "scale(500)",
						opacity: 0,
					},
				},
			},
			transitionProperty: {
				gridTemplateColumns: "grid-template-columns",
			},
			animation: {
				ripple: "ripple 1s cubic-bezier(0, 0, 0.2, 1) infinite",
			},
		},
	},
	plugins: [],
};
